pipeline:
    name: test2
    identifier: test2
    projectIdentifier: cmproj
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stage
              identifier: stage
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approvalzsdf
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.approvers
                                    approverInputs: []
              tags: {}
