pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.approvers
                                        minimumCount: <+input>
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                    approvalMessage: <+input>
                                name: Approval
                                identifier: approval
              name: xcvb
              identifier: xcvb
              variables:
                  - name: test
                    type: String
                    value: ""
    projectIdentifier: cmproj
    orgIdentifier: default
    name: harnessChange2
    identifier: xcb
    extraField: test
    tags: {}
    variables:
        - name: pipelinetest
          type: String
          value: ""
