pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.approvers
                                        disallowPipelineExecutor: false
                                        minimumCount: 1
                                    approvalMessage: asfd
              name: xcvb
              identifier: xcvb
    orgIdentifier: default
    projectIdentifier: cmproj
    name: harnessChange1
    identifier: xcb
    extraField: test
    tags: {}
