pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.approvers
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                name: Approval
                                identifier: approval
              name: xcvb
              identifier: xcvb
    projectIdentifier: cmproj
    orgIdentifier: default
    name: test6
    identifier: xcb
