pipeline:
    name: test-pipelines
    identifier: testpipelines
    projectIdentifier: cmproj
    orgIdentifier: FF_SDK_Tests
    tags: {}
    stages:
        - stage:
              name: testytest
              identifier: test
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.qatargetk8s
                          namespace: asfd
                  serviceDependencies:
                      - identifier: asfd
                        name: asfd
                        type: Service
                        spec:
                            connectorRef: harnessImage
                            image: asdf
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: asdf
                                identifier: asdf
                                spec:
                                    connectorRef: harnessImage
                                    image: asdf
                                    command: asfd
                                    privileged: false
    properties:
        ci:
            codebase:
                connectorRef: conorconnector
                build: <+input>
